# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: 2024.01.24
_src_path: gh:scientific-python/cookie
backend: hatch
email: alanlujan91@gmail.com
full_name: Alan Lujan
license: MIT
org: alanlujan91
project_name: SequentialEGM
project_short_description: A great package.
url: https://github.com/alanlujan91/SequentialEGM
vcs: false
