repos:
  - repo: https://github.com/mwouts/jupytext
    rev: v1.14.6
    hooks:
      - id: jupytext
        args: [--sync, --set-formats, "ipynb,py:percent", --pipe, black]
        additional_dependencies: [jupytext, black, nbconvert]
        files: ^code/.*\.ipynb$

  - repo: https://github.com/psf/black
    rev: 23.3.0
    hooks:
      - id: black
        exclude: ^code/.*\.ipynb$

  - repo: https://github.com/asottile/pyupgrade
    rev: v3.6.0
    hooks:
      - id: pyupgrade
        args: ["--py310-plus"]
        exclude: ^code/.*\.ipynb$

  - repo: https://github.com/asottile/blacken-docs
    rev: 1.13.0
    hooks:
      - id: blacken-docs
        exclude: ^code/.*\.ipynb$

  - repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
      - id: isort
        name: isort (python)
        args: ["--profile", "black", "--filter-files", "--skip", "__init__.py"]
        exclude: ^code/.*\.ipynb$

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: requirements-txt-fixer
        exclude: ^code/.*\.ipynb$
