name: egmn-dev
channels:
  - conda-forge
dependencies:
  - python=3.10
  - scipy
  - matplotlib
  - numpy
  - numba<0.59
  - scikit-learn
  - pandas
  - sympy
  - ipympl
  - nodejs
  - mystmd
  - estimagic
  - pip
  - pip:
      - git+https://github.com/alanlujan91/HARK@map_coordinates
      - ConSav
      - EconModel
      - black[jupyter]
