name: egmn-dev
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - black
  - estimagic
  - ipympl
  - jupyter
  - jupyterlab
  - jupyterlab-deck
  - jupyter-book
  - jupytext
  - matplotlib
  - networkx
  - notebook
  - numba
  - numpy
  - pandas
  - pip
  - pre-commit
  - scikit-learn
  - scipy
  - seaborn
  - sympy
  - statsmodels
  - xarray
  - ruff
  - pip:
      - git+https://github.com/alanlujan91/HARK@map_coordinates
      - ConSav
      - EconModel
      - black[jupyter]
