name: egmn-dev
channels:
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - adaptive
  - black
  - cloudpickle
  - cupy
  - distributed
  - estimagic
  - holoviews
  - ipykernel>=4.8*
  - ipympl
  - ipyparallel>=6.2.5
  - ipywidgets
  - jupyter_client>=5.2.2
  - jupyterlab
  - jupytext
  - loky
  - matplotlib
  - networkx
  - notebook
  - numba
  - numpy
  - pandas
  - pip
  - plotly
  - pre-commit
  - python=3.9
  - scikit-learn
  - scikit-optimize>=0.8.1
  - scipy
  - seaborn
  - sortedcollections
  - sortedcontainers
  - statsmodels
  - xarray
  - pip:
      - git+https://github.com/alanlujan91/HARK@map_coordinates
      - ConSav
      - EconModel
      - adaptive[notebook]
