name: egmn-dev
channels:
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - black
  - cupy
  - estimagic
  - ipympl
  - jupyterlab
  - jupytext
  - matplotlib
  - networkx
  - notebook
  - numba
  - numpy
  - pandas
  - pip
  - pre-commit
  - python=3.10
  - scikit-learn
  - scipy
  - seaborn
  - statsmodels
  - xarray
  - pip:
      - git+https://github.com/alanlujan91/HARK@map_coordinates
      - ConSav
      - EconModel
